### ISSUE TITLE
New version of Elmish.Toast compatible with Elmish 3 and without Fable.PowerPack

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#100]
Would it be possible to publish a new version of Thoth.Elmish.Toast compatible with Elmish 3 and without the Fable.PowerPack dependency? You can use the new Fable.Promise package, but as you only need to wait for a few milliseconds, you can also just use `Async.Sleep` and `Cmd.ofAsync` to avoid an extra dependency only for that.

It'd be interesting to remove the CSS imports to see if this helps with the bundle size, but it can affect other users and I'm not still sure this is what is preventing module concatenation, so it's not really a big priority.

**Comment by MangelMaxime** [comment]
About the CSS imports I think in the next version I will use inline style just like I did for FormBuilder.

https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Elmish.FormBuilder/Form.fs#L58-L88
