### ISSUE TITLE
Unable to run Mocha Tests

### ISSUE THREAD

**Issue by rfrerebe** [MangelMaxime/Thoth#106]
Hello,

I am working to add timespan to Thoth, but I am unable to run Tests from current version 77caf44fe5cdb5a44843224e4588be9087d418d8

when running 
`fake build -t ExpectoTest`

I get 
```
Error is 
Starting target 'MochaTest'
Starting task 'DotNet:version': running dotnet --version
D:\DEV\Thoth> "C:\Program Files\dotnet\dotnet.EXE" --version (In: false, Out: true, Err: true)
2.1.402
Finished (Success) 'DotNet:version' in 00:00:00.1600861
D:\DEV\Thoth\tests> "C:\Program Files\dotnet\dotnet.EXE" fable fable-splitter -- -c tests/splitter.config.js (In: false, Out: false, Err: false)
Fable (2.0.11) daemon started on port 65323
CWD: D:\DEV\Thoth
cmd /C "D:\DEV\Thoth\node_modules/.bin/fable-splitter.cmd" -c tests/splitter.config.js
D:\DEV\Thoth\node_modules\fable-splitter\dist\index.js:19
    throw new Error("This version is not compatible with dotnet-fable cli tool, "
    ^

Error: This version is not compatible with dotnet-fable cli tool, see https://www.npmjs.com/package/fable-splitter#usage
    at Object.<anonymous> (D:\DEV\Thoth\node_modules\fable-splitter\dist\index.js:19:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\DEV\Thoth\node_modules\fable-splitter\dist\cli.js:6:17)
    at Module._compile (module.js:653:30)
Closing Fable daemon...
Finished (Failed) 'MochaTest' in 00:00:01.4564324
```

I able to run tests only from c1bdb4c4f4df4cccc822424bc7bd5ea47deb0f5d

**Comment by MangelMaxime** [comment]
Hello, 
will be fixed by https://github.com/MangelMaxime/Thoth/pull/84

You can start your PR from this PR as it approved in principle. I am just waiting to work on the documentation.

**Comment by xdaDaveShaw** [comment]
Even with the code in #84 you cannot run the Docs Targets because of the same error, these will need updating too.

I don't know if you want to do it in #84 or just have a separate PR afterwards to update everything from Fable 2.0 to 2.1?

**Comment by MangelMaxime** [comment]
Hum, in theory from this commit https://github.com/MangelMaxime/Thoth/pull/84/commits/4e309d9815651267ef71c03f0ad6a769d1743be7 all the target should be working.

I just tried again locally as if it was a fresh repo (`git clean -dxf`) and for me:
- `ExpectoTest` is ✅ 
- `Docs.Build` is ✅

**Comment by xdaDaveShaw** [comment]
Yep, that did it, thanks. I think I built master before pulling this branch and applying my changes.

**Comment by rfrerebe** [comment]
It works now . Thanks
