### ISSUE TITLE
[Toast] Group notifications together

### ISSUE THREAD

**Issue by xdaDaveShaw** [MangelMaxime/Thoth#108]
As per this REPL issue: https://github.com/fable-compiler/repl/issues/46

@MangelMaxime suggested:

>The feature I have in mind is to allow user attach a "group" to a Toast and say. I only want one Toast of this group displayed at a time.
If there is already a toast of the same group in the stack then it will be removed and the new one is added. This feature also needs to add transition/animation support so people can see the old toast being removed when the new one is added.

**Comment by xdaDaveShaw** [comment]
I'm happy to have a go at the F# changes for this - doesn't look too complicated... but I'd be stuck on the CSS changes needed to make the transition effects.

**Comment by MangelMaxime** [comment]
You can skip the CSS part as it is secondary for this feature. 

When the feature is complete I can either work with you on the CSS side or implement it myself :)

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
