### ISSUE TITLE
Add support for enumeration in auto coders

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#126]
I forgot to add support for enumeration in my last PR :/ It's easy to add extra coders for an enum type [like this](https://gist.github.com/alfonsogarciacaro/11e0aa8acc87cbbca8948e2cdfae15b4). However users will probably expect this can be done automatically by Thoth.

It's not difficult to do it for .NET but unfortunately there's no support for `x.GetType().IsEnum` in Fable at the moment. We'll need it in order to identify enumeration types in the runtime.

**Comment by MangelMaxime** [comment]
#161 

Support for the following types:

* Add supports for `enum<byte>`
* Add supports for `enum<sbyte>`
* Add supports for `enum<int16>`
* Add supports for `enum<uint16>`
* Add supports for `enum<int>`
* Add supports for `enum<uint32>`

Released in:

- Thoth.Json 3.4.0
- Thoth.Json.Net 3.6.0
