### ISSUE TITLE
[FormBuilder] Should Form.render render a form-tag?

### ISSUE THREAD

**Issue by viktorvan** [MangelMaxime/Thoth#127]
Maybe I am not using the Formbuilder correctly, but when rendering the view with `Form.render` the rendered html is:
```html
<div class="thoth-form">
   ...
</div>
```
I expected it to have a `<form>`-tag?

As far as I can tell the form-tag is required for example to get Chrome to validate an email-input in the browser. So to get that to work I have to add the form tag manually:
```fsharp
form [] [ Form.render myProps ]
```

Am I missing something or do I need to add the form-tag manually?
If this is the case maybe it could be reflected in the demos/documentation?

**Comment by MangelMaxime** [comment]
This is expected because a `form` tag will have some default behavior. For example, if you have a submit button in it, will send itself. So you will have to listen to `OnSubmit` and cancel the event etc.

You can wrap it in a `form` tag if you want this behavior.

**Comment by viktorvan** [comment]
Thanks for the explanation, that makes sense. I mostly do backend development, so I was guessing there was a reason for this behaviour. :)
