### ISSUE TITLE
Latest Fable 2.2 beta brings compiler warning

### ISSUE THREAD

**Issue by forki** [MangelMaxime/Thoth#129]
![image](https://user-images.githubusercontent.com/57396/53411241-4676a800-39c6-11e9-8b6a-f3f34c361820.png)

**Comment by MangelMaxime** [comment]
Does Thoth.Json v3 generates the warning?

It's marked in beta stage, but it's stable and the changes was made to improve extensibility of `Auto` decoders/encoders

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/53412582-09141980-39ca-11e9-918b-9fd6a369db3b.png)

yep

**Comment by MangelMaxime** [comment]
cc @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
This should be fixed in the next fable-compiler beta release :)
