### ISSUE TITLE
IE 11 serialization problem

### ISSUE THREAD

**Issue by halcwb** [MangelMaxime/Thoth#130]
When trying to serialize an object like:

`["PatientMsg",["Calculate",{"Age":{"Years":6,"Months":0,"Weeks":0,"Days":0},"Weight":{"Estimated":15,"Measured":15},"Height":{"Estimated":98,"Measured":0}}]]`

in IE, what is created is:

`["PatientMsg",["Calculate",[]]]`

So the object in the discriminated union is not serialized in IE 11.

**Comment by MangelMaxime** [comment]
Hello @halcwb,

Do you have a warning/error in the console?

Are you using auto or manual coders?

Could you please provide reproduction code?
- Domain types
- Decoders/Encoders used

**Comment by halcwb** [comment]
Hello @MangelMaxime 

This is the code I use to send a request using Thoth encoding:

```
    let post req =
        let decode = Decode.Auto.unsafeFromString<Response Option>
        promise { let! res = postRecord "/api/request" req []
                  let! resp= res.text()
                  return resp |> decode }

    let requestToResponseCommand respMsg reqMsg =
        reqMsg
        |> post
        |> (fun task ->
        Cmd.ofPromise (fun () -> task) () (Ok >> respMsg)
            (Result.Error >> respMsg))

```
Well, actually it is the postRecord method which performs the serialization, but this in turn uses Thoth.Json as well, I think.

**Comment by halcwb** [comment]
As a related issue, I discovered that the powerpack lib is no longer in use. The postRecord depends both on Fable.Fetch and Fable.Promise. So, this function is deprecated as well. It is rather trivial to create the function yourself. But when people upgrade to the seperate Fable.Fetch and Fable.Promise, this could be a bit of a surprise.

**Comment by MangelMaxime** [comment]
> To be sure, the `req` is a discriminated union type that wraps an object in various 'request layers, i.e. discriminated union types' as shown in my example above.

Having a reproduction types would helps, so is your type of the form:

```fs
type Data =
    { Value : int }

type NestedUnion =
    | Data of Data

type Repro =
    | CaseA of NestedUnion
```

> As a related issue, I discovered that the powerpack lib is no longer in use. The postRecord depends both on Fable.Fetch and Fable.Promise. So, this function is deprecated as well. It is rather trivial to create the function yourself. But when people upgrade to the seperate Fable.Fetch and Fable.Promise, this could be a bit of a surprise.

Yes, we decided to split the `Fable.PowerPack` package and some people complained because it was using `Thoth.Json` internally. So `Thoth.Json` was included in their project even if they wanted to use another JSON library.

A solution could be to create a `Thoth.Fetch` package or something like that which port [this code](https://github.com/fable-compiler/fable-fetch/blob/master/src/Fetch.fs#L358-L408).

It could be accessible from `Thoth.Fetch.putRecord `.

**Comment by MangelMaxime** [comment]
Thank you for the reproduction code :)

It will help work on the issue.

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
