### ISSUE TITLE
Support for net40 in Thoth.Json.Net

### ISSUE THREAD

**Issue by theimowski** [MangelMaxime/Thoth#131]
I have an app using net40 and would like to use Thoth.Json for serialisation.
Currently the project supports net46 - do you think it would be reasonable to add support for net40 as well?

**Comment by MangelMaxime** [comment]
I don't have much experience of .Net but if Newtonsoft is available for this version it's should be do-able.

I am finishing the split of this repo this evening in theory and after that I can take a look at this issue or accept PR again.

**Comment by theimowski** [comment]
I'm happy to submit a PR - will start looking into what needs to be done

**Comment by theimowski** [comment]
I managed to hack out a net40 nupkg for Thoth.Json.Net - https://github.com/theimowski/Thoth/commit/c445ba75f94f4c17e20c1c5315d1a9db50fc6e0e 
For now I'll just embed the nupkg for my project.
Let me know when you split the repository so that I can work on cleaning up the change and submit a PR to officially support net40

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
