### ISSUE TITLE
Thoth.Json: allow decoding of classes when value is null

### ISSUE THREAD

**Issue by 0x53A** [MangelMaxime/Thoth#132]
I am using Fable Elmish React with ServerSideRendering.

My Model contains a mutable ``System.Collections.Generic.Dictionary`` as a cache.

On deserialization of the model I get an exception:

```
Error: Error at: `$.PageModel.SlabCache` I run into a `fail` decoder: Class types cannot be automatically deserialized: System.Collections.Generic.Dictionary`2[ebosYC.Domain.SlabId,Fable.Import.JS.Promise`1[System.Tuple`2[]]]
```

When I render the page on the server, I set the cache to ``null``.

I haven't looked at the code of Thoth yet, but what would you think about emiting a special decoder that only accepts null when encountering an unknown class type?

**Comment by MangelMaxime** [comment]
> a special decoder that only accepts null when encountering an unknown class type?

This kind of defeat the purpose of this library. The error you get from

**Comment by 0x53A** [comment]
I changed it to ``Dictionary<_,_> option`` and now it works (with 2.x).

As long as the value sent from the server is None, it correctly deserializes.

**Comment by MangelMaxime** [comment]
Indeed, when using `'T option` if you send `null` the auto decoder will work. It was added for people using F# on client and server side.
