### ISSUE TITLE
Encoding of DateTime is inconsictent and maybe wrong

### ISSUE THREAD

**Issue by irgendwienet** [MangelMaxime/Thoth#137]
.net knows three kinds of DateTime values: `Unspecified`, `Local` and `Utc`

When encoding DateTime values of these kinds, `Encode.datetime` and `Encode.Auto.toString` produce different results. That was very unexpected to me.

The following code

        let local = DateTime(2000,1,1,0,0,0,0, DateTimeKind.Local)
        Logger.log "local"
        Logger.log (Thoth.Json.Encode.Auto.toString (1, local))
        Logger.log (Thoth.Json.Encode.datetime (local))

        let un = DateTime(2000,1,1,0,0,0,0, DateTimeKind.Unspecified)
        Logger.log "unspecified"
        Logger.log (Thoth.Json.Encode.Auto.toString (1, un))
        Logger.log (Thoth.Json.Encode.datetime (un))

        let utc = DateTime(2000,1,1,0,0,0,0, DateTimeKind.Utc)
        Logger.log "utc"
        Logger.log (Thoth.Json.Encode.Auto.toString (1, utc))
        Logger.log (Thoth.Json.Encode.datetime (utc))

produces this output (Running in Chrome on a machine with the german time zone)

		local
		"1999-12-31T23:00:00.000Z"
		2000-01-01T00:00:00.000+01:00

		unspecified
		"1999-12-31T23:00:00.000Z"
		2000-01-01T00:00:00.000

		utc
		"2000-01-01T00:00:00.000Z"
		2000-01-01T00:00:00.000Z

I expected at least for each kind that both encodings represent the same value. From my point of view the result of `Encode.datetime` is the right way to represent the different kinds of DateTime value. (The "Z" for UTC, no postfix for unspecified and the correct date and time with "+01:00" as time zone for local time).

A third party component created values of `Kind.Unspecified` am Midnight (e.g. 2000-01-01T00:00) for me, that where processed by Thoth / Fable to a JSON with `"1999-12-31T23:00:00.000Z"`. 
As a backend we use ASP.NET core and this value was decoded to a DateTime in the year 1999 without timezone (since there is no timezone in the DateTime type).

**Comment by MangelMaxime** [comment]
Hello @irgendwienet ,

sorry for the delay, I have been busy with the Fable.Core v3 updates lately. 

In theory, this problem has been solved in `Thoth.Json v3` so if you make the update it should be fine.

Here is the output I get:

```fs
local 
"2000-01-01T00:00:00.000+01:00" 
2000-01-01T00:00:00.000+01:00 

unspecified 
"2000-01-01T00:00:00.000" 
2000-01-01T00:00:00.000 

utc 
"2000-01-01T00:00:00.000Z" 
2000-01-01T00:00:00.000Z
```

Before Thoth.Json v3, auto coders where using another implementation than manual coder. Now they are using manual coder under the hood to garantee the same behavior when using one or another.

Please feel free to re-open, if the issue still exist in your case.
