### ISSUE TITLE
Documentation for collection deserialization snippet needs to be fixed

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [MangelMaxime/Thoth#139]
Using  Thoth.Json (2.5) (per my paket.lock file)
following https://mangelmaxime.github.io/Thoth/json/v2.html
the collections sections shows `Decode.fromString (array int) "[1, 2, 3]"` which does not compile with only the shown above `open Thoth.Json`
The syntax showing up in intellisense wants a decoder before you can pass a value to `Decode.fromString`
I believe `array int` isn't legal syntax outside of type annotations and generic calls.

Is the issue a missing namespace import, wrong doc version, wrong documentation, or something else?

**Comment by MangelMaxime** [comment]
Hello, 

this is an error in the documentation.

You should use:

```fs
open Thoth.Json

Decode.fromString (Decode.array Decode.int) "[1, 2, 3]"
```

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
