### ISSUE TITLE
[JSon] no decoders for float32 / byte

### ISSUE THREAD

**Issue by 0x53A** [MangelMaxime/Thoth#140]
![image](https://user-images.githubusercontent.com/4236651/57225145-ce52e100-700b-11e9-9c80-d8bc7fb6772d.png)

![image](https://user-images.githubusercontent.com/4236651/57225152-d743b280-700b-11e9-9d4e-f1ddc49d0e81.png)

In JS, the distinction between float64 and float32 doesn't really matter, so I added this:

```fs
let inline withFloat32 (extra: ExtraCoders): ExtraCoders =
    Map.add typeof<float32>.FullName (Encode.boxEncoder Encode.float, Decode.boxDecoder Decode.float) extra
```

Same for byte.

Do you think decoders for float32 (System.Single) and uint8 (System.Byte) can be added to the core?

**Comment by MangelMaxime** [comment]
Hello, I created the issue in the new.

I still need to finish the repo split thing :)
