### ISSUE TITLE
Decode.string fails on strings with datetime

### ISSUE THREAD

**Issue by dbrattli** [MangelMaxime/Thoth#142]
Looks like `Decode.string` fails with this string. Using Thoth.Json.Net (3.1) Newtonsoft.Json (12.0.1). Anyone that can repro this?

```fs
Decode.fromString Decode.string "\"2018-08-06T10:06:40.000\""
```

```
"Error at: `$` Expecting a string but instead got: "2018-08-06T10:06:40""
```

Probably because it's a datetime, perhaps related to https://stackoverflow.com/questions/11856694/json-net-disable-the-deserialization-on-datetime

**Comment by MangelMaxime** [comment]
The issue has been moved to https://github.com/thoth-org/Thoth.Json.Net/issues/13

*Following the repo split, I am working on making this repo read-only to avoid people opening the issue in the old repo*
