### ISSUE TITLE
Thoth.Json.Net.Converters are missing in 3.0

### ISSUE THREAD

**Issue by SCullman** [MangelMaxime/Thoth#143]
I noticed that Thoth.Json.Net.Converters are removed. I used them to communicate via WebApi with 2.5.0,

```fsharp
open Thoth.Json.Net.Converters

type WithThothJsonNetConverterAttribute () =
   inherit System.Attribute()

   interface IControllerConfiguration with
      member __.Initialize ( (controllerSettings:HttpControllerSettings) , _ ) =
      
        let converter = CacheConverter(converters)

        let thothFormatter = 
           JsonMediaTypeFormatter ( SerializerSettings = JsonSerializerSettings ( Converters = [|converter|] ) )
        controllerSettings.Formatters.Clear ()
        controllerSettings.Formatters.Add thothFormatter


[<WithThothJsonNetConverter>]
type FableController () =
  inherit ApiController ()
...
```

Any workaraound? Can it be rolled back? I cannot switch to .Net Core yet.

**Comment by MangelMaxime** [comment]
Sorry but `Thoth.Json.Net.Converters` has been removed and will not be added back.

The reason, is they output a different code compared to manual decoders. Version 3 of the library has been focused on making manual and auto coder transparent. So using manual coder or an auto coder will have the same result.

> I cannot switch to .Net Core yet.

Thoth.Json.Net support both .Net Core and .NET Framework so perhaps you can still use it. In theory, version 2 and 3 support the same version of .NET Framework.

I know nothing about WebApi but I suppose it is not tied to Newtonsoft. So you should be able to Thoth.Json.Net v3 if you find how to hook it up in the WebApi architecture.

**Comment by SCullman** [comment]
> So you should be able to Thoth.Json.Net v3 if you find how to hook it up in the WebApi architecture.

That's my main problem. So far I didn't have to worry about it. 

If I understand your comment correctly, I can't run both versions: The old converter in the Asp.Net WebApi  on server side, and Thoth.Json 3. x on client side does not work together because the auto coders serializes differently?

**Comment by MangelMaxime** [comment]
> The old converter in the Asp.Net WebApi on server side, and Thoth.Json 3. x on client side does not work together because the auto coders serializes differently?

Hum, I guess most of the types should works. But I can't guarantee it

**Comment by MangelMaxime** [comment]
But perhaps, you can fix/override the types that would not work out the box. By using the extra coder features added in v3.
