### ISSUE TITLE
Cannot auto encode DateTimeOffset option

### ISSUE THREAD

**Issue by grishace** [MangelMaxime/Thoth#144]
```
Error at: `$` I run into a `fail` decoder: Cannot find case Cannot generate auto encoder for System.Nullable`1[[System.DateTimeOffset, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]. Please pass an extra encoder. in Microsoft.FSharp.Core.FSharpResult`2[System.Tuple`3[System.String,System.String,Microsoft.FSharp.Core.FSharpOption`1[System.DateTimeOffset]],System.String]
```

**Comment by grishace** [comment]
I don't see how I could pass `an extra encoder`. into the generic type.

**Comment by MangelMaxime** [comment]
Hello, 

in order to help you, I will need a reproduction code and also can you please tell me which library is causing this exception?

**Comment by grishace** [comment]
@MangelMaxime It was my fault mixing Nullable<DateTimeOffset> with DateTimeOffset option.

**Comment by MangelMaxime** [comment]
Yes, Thoth.Json consider `null` as invalid value for `DateTime`, `DateTimeOffset`, etc.

It considers that `null` is represented using `'T option`. It's more or less like `null` don't exist as a valid type for a class for Thoth.Json we could say.
