### ISSUE TITLE
Should Thoth.Json.Net.dll in the nupkg lib reference the minimum dependency version of Newtonsoft.Json?

### ISSUE THREAD

**Issue by bentayloruk** [MangelMaxime/Thoth#147]
Hi Thothers!

I've tried to figure this out, but failed, so hoping someone in here will have the knowledge.

I have a problem which I *think* stems from the fact that the [`Thoth.Json.Net`](https://www.nuget.org/packages/Thoth.Json.Net/3.0.0) nuspec specifies `<dependency id="Newtonsoft.Json" version="11.0.2" />` but the  `nupkg/lib/netstandard2.0/Thoth.Json.Net.dll` references version `12.0.0.0`.

Here is the nuspec for 3.0.0:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/189409/58664968-14d6eb00-82ed-11e9-8459-2a9c70287c07.png">

And here is the lib reference (via ILSpy):
<img width="688" alt="image" src="https://user-images.githubusercontent.com/189409/58664461-e7d60880-82eb-11e9-9aac-01f91c1b00e5.png">

In our case, `Thoth.Json.Net` is a dependency of our first assembly A and then we reference A from our second assembly B.  We then reference assembly B from a web project, where the dependencies are managed by Nuget, not Paket.  In this situation, `Thoth.Json.Net` is a transitive dependency of our web application and as a result, so is `Newtonsoft.Json`.  Nuget correctly identifies this, reads the nuspec for Thoth and based on that decides we are fine with version `11.0.2` of `Newtonsoft.Json` (I think Nuget defaults to the earliest version of the dependency?).  However, at runtime our web application fails because `Thoth.Json.Net` tries to load version `12.0.0.0`.

I've done a bunch of Googling, but have been unable to determine how I'm supposed to handle this in the .NET Core world (in the old world I might have tried a ["downgrade" assembly binding](https://stackoverflow.com/a/17108316/418492)).  On the surface it would seem sensible to me that the lib distribution of `Thoth.Json.Net` should reference the minimum version of it's dependencies in order to avoid this, but maybe I'm missing something and this is a scenario that should be fine?  If so, does anyone know the incantations I need to mumble?

*I'm currently working around this by adding version 12 of Newtonsoft as a top level PackageReference in my web project, but that is not ideal.*

**Comment by bentayloruk** [comment]
Bit of extra information to confirm the result of the [PackageReference resolution](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#dependency-resolution-with-packagereference).  Here is the part of `/obj/project.assets.json` showing the resolved version of `Newtonsoft.Json`:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/189409/58722170-faa41800-8393-11e9-9127-a539cd58f515.png">

**Comment by MangelMaxime** [comment]
Hello,

I am indeed fine by making Thoth.Json.Net reference 11.0.2 which is the minimal version marked as accepted in [paket.dependencies](https://github.com/thoth-org/Thoth.Json.Net/blob/master/paket.dependencies#L7).

I just don't know how to do it. 

@bentayloruk Do you know what changes are needed in order to make it happen?

For info, Thoth.Json.Net is now hosted [here](https://github.com/thoth-org/Thoth.Json.Net). If you want to submit a PR :)

**Comment by bentayloruk** [comment]
@MangelMaxime yes, I will raise a PR.  I've re-raised the issue in the new repos and will close this one too!
