### ISSUE TITLE
Thoth.Json.Net depends on Fable.Core and Fable.Core shouldn't be on the server

### ISSUE THREAD

**Issue by Neftedollar** [MangelMaxime/Thoth#148]
Hey!
Thoth.Json.Net depends on Fable.Core and Fable.Core shouldn't be on the server.

**Comment by MangelMaxime** [comment]
`Thoth.Json.Net` depends on `Fable.Core` in order to support `StringEnum`attributes [see this issue](https://github.com/thoth-org/Thoth.Json.Net/issues/11).

So this is normal.

**Comment by Neftedollar** [comment]
How can I remove this warning?
```sh
C:\Users\...\src\function.fsproj : warning NU1603: Thoth.Json.Net 3.4.0 depends on Fable.Core (>= 0.0.0) but Fable.Core 0.0.0 was not found. An approximate best match of Fable.Core 1.0.1 was resolved.
```
It's really annoying

**Comment by Neftedollar** [comment]
@MangelMaxime ^

**Comment by MangelMaxime** [comment]
Upgrade to version `3.5.1` this should be solved in this version.

**3.4.0 dependencies**
<img width="397" alt="Capture d’écran 2019-07-12 à 11 49 28" src="https://user-images.githubusercontent.com/4760796/61119476-36ee8c00-a49b-11e9-9ffb-4feb028f7ded.png">

**3.5.1 dependencies**
<img width="359" alt="Capture d’écran 2019-07-12 à 11 49 33" src="https://user-images.githubusercontent.com/4760796/61119498-3e159a00-a49b-11e9-995c-5db37905524f.png">

**Comment by Neftedollar** [comment]
@MangelMaxime 
Thank you very very very mach!
