### ISSUE TITLE
Auto encode omits fields with a value of `None`

### ISSUE THREAD

**Issue by mattfurness** [MangelMaxime/Thoth#149]
At the moment the code below:

```fsharp
type Foo =
    { bar : string
      baz : string option }

let foo =
    { bar = "Bar"
      baz = None }

let encoder = Thoth.Json.Net.Encode.Auto.generateEncoder<Foo> ()

Encode.toString 2 <| encoder input
```

Results in json of:

```json
{
  "bar": "Bar"
}
```

Notice that the `baz` field is not in the json string because it has a value of `None`. This [appears to be intentional](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Json.Net/Encode.fs#L341-L343). I am working in an app where it is preferable to include the field with a value of `null`, so the output would be:

```json
{
  "bar": "Bar",
  "baz": null
}
```

Would you be happy for me to submit a PR that makes this possible and configurable?

**Comment by rmunn** [comment]
Configurable is good, because the current behavior (omitting optional fields whole value is None) was exactly what I wanted in my current project.

**Comment by MangelMaxime** [comment]
In the next version of Thoth.Json, you will be able to set this behaviour via an optional argument:

```fs
            testCase "Encode.Auto.toString emit null field if setted for" <| fun _ ->
                let value = { fieldA = null }
                let expected = """{"fieldA":null}"""
                let actual = Encode.Auto.toString(0, value, skipNullField = false)
                equal expected actual
```

By default, it will skip the field when the value is `null` (same behaviour as the current version)

**Comment by MangelMaxime** [comment]
Released in:

- Thoth.Json 3.4.0
- Thoth.Json.Net 3.6.0
