### ISSUE TITLE
Thoth.Json.Giraffe parses UTC datetime to undefined datetime 

### ISSUE THREAD

**Issue by christoph-feb22** [MangelMaxime/Thoth#150]
Hi,

when using the Thoth.Json.Giraffe serializer I always get datetime strings of format unspecified (2019-06-17T00:00:00) without the timezone specifier.
The requests sends the datetime string in utc format (2019-06-17T00:00:00Z).

I am using Thoth.Json.Giraffe version 2.1 and Thoth.Json.Net 3.4

**Comment by christoph-feb22** [comment]
While trying to create a reproduction example I noticed, everything works correct in a fsx file using the same dll. So I cleaned my bin and obj directory in my app and now it works correct.
So it seems like it was a bug in the version I used before updating.

Thanks for your fast response @MangelMaxime

**Comment by MangelMaxime** [comment]
@christoph-feb22 Thank you for trying to reproduce and happy that it's fixed :)
