### ISSUE TITLE
Encode.toString and JsInterop.toJson output are different with discriminated union

### ISSUE THREAD

**Issue by bruno-cadorette** [MangelMaxime/Thoth#159]
Hello, we're currently upgrading our app from Fable 1 to Fable 2 and we ran into an issue. Currently, we use `JsInterop.toJson` to serialize our data. [This blog post](https://fable.io/blog/Migration-to-Fable2.html) say to use `Encode.Auto.toString(0, x)`. With this code I'm getting different results for both serialization

    type Baz =
        {
            F1: int
            F2: int
            F3: int
            F4: int
        }
    type Bar =
        | A
        | B of Baz
    type Foo =
        {
            Value: Bar
        }

    let b = B {F1 = 1; F2 = 2; F3 = 3; F4 = 4}
    let v = {Value = b}

Fable 1:
`JsInterop.toJson b` output `{"B":{"F1":1,"F2":2,"F3":3,"F4":4}}`
`JsInterop.toJson v` output `{"Value":{"B":{"F1":1,"F2":2,"F3":3,"F4":4}}}`

Fable 2:

`Encode.Auto.toString(0, b)`  output ` ["B",{"F1":1,"F2":2,"F3":3,"F4":4}]`
`Encode.Auto.toString(0, v)`  output `  {"Value":["B",{"F1":1,"F2":2,"F3":3,"F4":4}]}`

Is there a workaround to have the same output in thoth? I also have the same issue with the deserialization

**Comment by MangelMaxime** [comment]
Thoth.Json doesn't aim to provide the same output as `JsInterop.toJson`.

Thoth.Json only guarantee that JSON generated from `Thoth.Json` or `Thoth.Json.Net` are compatible with each other. If you are still using `Fable.Converter` on the backend you should replace it with `Thoth.Json.Net`

[Documentation](https://mangelmaxime.github.io/Thoth/json/v3.html#net-netcore-support)

**Comment by bruno-cadorette** [comment]
Thank you!
