### ISSUE TITLE
Support Enums

### ISSUE THREAD

**Issue by et1975** [MangelMaxime/Thoth#161]
FSharp doesn't consider the type:
```fsharp
type X = One = 1 | Two = 2
```
to be a union, but it would be nice if Thoth could handle it automatically, deserializing both `int` and `string` values. 
Currently the decoding raises no issues, but the deserialized values lack something and don't work with pattern matching:
```fsharp
let x = deserialized "One" // or deserialized 1
match x with
| One -> "one"
| x -> string x
```
results in `[object Object]`.

**Comment by MangelMaxime** [comment]
Ok this is due to a bug in Fable compiler.

When writing:

```fs
type X = 
    | One = 1 
    | Two = 2

let json = Encode.Auto.toString<X>(4, X.One)
```

we get:

```js
export const X = declare(function Test_X(arg1, arg2, arg3) {
  this.value__ = arg1 | 0;
  this.One = arg2;
  this.Two = arg3;
}, Record);
export function X$reflection() {
  return type("Test.X");
}
export const json = Auto$0024$0024$0024toString$0024$002459982D9A(4, 1, null, null, {
  ResolveType() {
    return int32;
  }

});
```

As you can see the type information is `int32`. So Thoth.Json is trying to decode the value as an `int` and because `1` is indeed an int then it's working.

I will have a look at this bug in Fable compiler and also tries to add the reflection info/methods needed to support enums (currently we don't have any reflection method available for enums) that's why Thoth.Json can't support them out the box and you have to provide your own coders for them.

**Comment by et1975** [comment]
I've got these custom decoder/encoder and it works, I just don't want to have to write those for each type of enum:
```fsharp
    let decoder _ (value:obj) : Result<X,_> =
        Ok (LanguagePrimitives.EnumOfValue (unbox value))

    let encoder (value: StageType) : JsonValue =
        Linq.JValue (LanguagePrimitives.EnumToValue value) :> JsonValue   
```

**Comment by MangelMaxime** [comment]
Other possible implementation, which seems to restrict the value to be an actual enum

*Sharing so I can have access to them on my other laptop*

```fs
let inline parseEnum (value : int) : ^TEnum =
    let enumType = typeof< ^TEnum>
    printfn "%A" enumType

    enum value

let inline toJsonEnum (value : ^TEnum when ^TEnum :> System.Enum) =
    string value

type Test =
    | One = 1
    | Two = 2

type Test2 =
    | One = 'o'
    | Two = 't'

let x : Test = parseEnum 2

printfn "%A" (toJsonEnum Test.One)
```

**Comment by MangelMaxime** [comment]
Support for the following types:

* Add supports for `enum<byte>`
* Add supports for `enum<sbyte>`
* Add supports for `enum<int16>`
* Add supports for `enum<uint16>`
* Add supports for `enum<int>`
* Add supports for `enum<uint32>`

Released in:

- Thoth.Json 3.4.0
- Thoth.Json.Net 3.6.0

**Comment by et1975** [comment]
Thank you!
