### ISSUE TITLE
\n in strings

### ISSUE THREAD

**Issue by et1975** [MangelMaxime/Thoth#162]
Thoth.Net is happy to send `"test\ntest"` "as is" from the .NET side, but fable side fails to deserialize it, [looks to be rightfully so](https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json), while Json.NET doesn't seem to have a problem deserializing it.

**Comment by MangelMaxime** [comment]
Can you please provide a reproduction code?

I just want to be sure, you are calling the serializer correctly. Because in theory, the correct JSON representation of that string should be something like `"\"test\\ntest\""`.

**Comment by et1975** [comment]
Sorry, it seems I misdiagnosed the issue, closing.
