### ISSUE TITLE
System.Text.Json

### ISSUE THREAD

**Issue by nojaf** [MangelMaxime/Thoth#164]
Hey Maxime,

Any ideas if [System.Text.Json](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) could be used in a future version of Thoth.Json.Net?

**Comment by MangelMaxime** [comment]
Hello,

It will depend on the exposed API from `System.Text.Json` but in theory yes. 

The plan for the next version of Thoth.Json is to allow the user to provide an interface which describes how to work with the JSON (basically it will replace the helpers module). The ideas, being people will then be able to share their code between the server and client without using compiler directives.

**Comment by nojaf** [comment]
Great, thanks for the reply.
Looking forward.
