### ISSUE TITLE
Thoth.Json.Net depends on Fable.Core

### ISSUE THREAD

**Issue by forki** [MangelMaxime/Thoth#165]
Thoth.Json.Net (3.5.1)
      Fable.Core (>= 3.0 < 4.0) - restriction: && (< net46) (>= netstandard2.0)
      FSharp.Core (>= 4.6.2) - restriction: || (>= net46) (>= netstandard2.0)
      Newtonsoft.Json (>= 11.0.2) - restriction: || (>= net46) (>= netstandard2.0)

I think this dependency on Fable.Core should be removed.

**Comment by MangelMaxime** [comment]
This is normal, we need it to support `StringEnums`

See https://github.com/MangelMaxime/Thoth/issues/148

We include `Fable.Core` only, for frameworks version supporting it.

**Comment by forki** [comment]
if I use netcoreapp3.0 then it shouldn't be there, right?

**Comment by MangelMaxime** [comment]
I don't know, are `netstandard2.0` libraries supported by `netcoreapp3.0`?

For example, if I remember correctly `netstandard1.6` was usable from `and co apps.
