### ISSUE TITLE
`Thoth.Json.Net` cannot find Union case

### ISSUE THREAD

**Issue by matthid** [MangelMaxime/Thoth#175]
```fsharp

open Fable.Core
open Thoth.Json.Net

[<StringEnum>]
type Test = 
 | Test1
 | TEST2

[<EntryPoint>]
let main argv =

    let t = TEST2
    printfn "%A" t
    let json = (Encode.Auto.toString(0, t))
    printfn "json %A" json
    let t2 : Test = Decode.Auto.unsafeFromString(json)
    printfn "res %A" t2

    0 // return an integer exit code
```

![image](https://user-images.githubusercontent.com/1866463/67491414-33ab9480-f675-11e9-8100-554be23b7295.png)

**Comment by matthid** [comment]
Interestingly not even `Test1` works. Do I use it wrong?

**Comment by MangelMaxime** [comment]
Before your second message, I would have said it's due to how Fable works:

```fs
open Fable.Core
open Fable.Core.JsInterop

[<StringEnum>]
type Test = 
    | Test1
    | TEST2
    | [<CompiledName("TEST3")>] TEST3

JS.console.log(Test.Test1)
JS.console.log(Test.TEST2)
JS.console.log(Test.TEST3)
```

Output:
```
test1
tEST2
TEST3
```

**Comment by matthid** [comment]
Ok as discussed in gitter this is mainly due to `[<StringEnum>]`

**Comment by MangelMaxime** [comment]
Just so I remember, it's due to `[<StringEnum>]` but still show that converting back and forth doesn't work on special cases. I need to cover them.

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
