### ISSUE TITLE
Add support for ASP.NET Core

### ISSUE THREAD

**Issue by nirvinm** [MangelMaxime/Thoth#176]
In ASP.NET Core 3, Newtonsoft.Json can replace default serializer by installing **Microsoft.AspNetCore.Mvc.NewtonsoftJson** package and configuring it with AddNewtonsoftJson() method in **Startup.fs** or Startup.cs

If Thoth can provide similar interface to replace ASP.NET serializer, it'll take away a lot of pain in configuring Thoth JSON in F# web applications written with ASP.NET Core.

**Comment by MangelMaxime** [comment]
Are you using ASP.NET Core directly or via Giraffe? 

Because we already provide this kind of support for Giraffe:

https://thoth-org.github.io/Thoth.Json/#Giraffe

**Comment by nirvinm** [comment]
@MangelMaxime I meant the stock ASP.NET Core with MVC not Giraffe.

**Comment by MangelMaxime** [comment]
@nirvinm Ok, sorry I am not using .Net daily and so learning a bit of it when people ask for new features :)

I am ok with experimenting for adding support of stock ASP.NET Core. 

Do you know how to hooks a custom JsonConverter to ASP.NET Core? Or do you know any documentation about it?

If you want to give it a try I can create a new repo (to host the new library) so you can send a PR to it and work from here together?

**Comment by nirvinm** [comment]
@MangelMaxime 

Have a look at this
[https://github.com/aspnet/AspNetCore/blob/471e4710a818849eaf22c5977281d10fd6758616/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonResultExecutor.cs](NewtonsoftJsonResultExecutor.cs)

Looks like we need to implement `IActionResultExecutor` that'll convert the result to Json and write it to the Response stream.

Yes it would be great if you can create a new package like `Thoth.Json.AspNetCore `which will replace the stock serializer with Thoth. I can help you implementing it.

**Comment by MangelMaxime** [comment]
Ok, thank you for the info.

I will create the repo tomorrow and ping you when it's available :)

**Comment by MangelMaxime** [comment]
Hello @nirvinm The repo is available [here](https://github.com/thoth-org/Thoth.Json.AspNetCore)

**Comment by nirvinm** [comment]
@MangelMaxime Thanks for creating the repo. I'm not an expert either in this area, so give me a couple of days so I can try implementing it.

**Comment by MangelMaxime** [comment]
Kamino closed and cloned this issue to [thoth-org/Thoth.Json.AspNetCore](https://github.com/thoth-org/Thoth.Json.AspNetCore/issues/2)
