### ISSUE TITLE
Encoding List2D doesn't work

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Thoth#22]
```fs

open Thoth.Json

let log x = Fable.Import.JS.console.log x

// This work
[| [| "maxime" |] |]
|> Array.map (fun d ->
    d
    |> Array.map Encode.string
    |> Encode.array
)
|> Encode.array
|> Encode.encode 4
|> log

// Result:
// [
//     [
//         "maxime"
//     ]
// ]

[ [ "maxime2" ] ]
|> List.map (fun d ->
    d
    |> List.map Encode.string
    |> Encode.list
)
|> Encode.list
|> Encode.encode 4
|> log

// Result:
// [
//     "maxime"
// ]

```

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro @Zaid-Ajaj If you have an idea why it's failing I am open to ideas :)

I suspect it's coming from the [encode implementation](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Json/Encode.js#L19-L27)

**Comment by alfonsogarciacaro** [comment]
```js
export function encodeList(values) {
    let array = [];
    while (values.head !== undefined) {
        array = array.concat(values.head);
        values = values.tail;
    }
    return array;
}
```

Hmm, that code should work (although it should be more performant to do `ar.push(values.head)` but I recommend making the list to array conversion in F#. For example, that JS code won't work with Fable 2. If you're concerned about types arrays, you can cast the list first to `obj list`.

**Comment by Zaid-Ajaj** [comment]
Hmm maybe because you are applying `encodeList` twice, the first time, you give it a list and return an array, the next time you run it, you are giving an array right? 

I cloned the repo to try out stuff but fake isn't working, i.e. `./fake.sh build -t Watch` could not restore the dependencies for fake itself (the bootstrapping phase) and I gave up. Is the repo still FAKE 4.x-compatible?

**Comment by MangelMaxime** [comment]
Hum, no it's using FAKE 5 only.

I think I know why it's failling when you do `./fake.sh build -t Watch` on an fresh repo.
Can you try run `./fake.sh build` first ?

`Watch`target is an "independant" target in current form. 
Not present in this list: https://github.com/MangelMaxime/Thoth/blob/master/build.fsx#L340-L355

It's probably a forgotten to fair ^^

**Comment by Zaid-Ajaj** [comment]
I actually added the dependencies for that target before running the command:
```
"Clean"
    ==> "YarnInstall"
    ==> "DotnetRestore"
    ==> "Watch"
```
And it didn't work either, I will check it again later

**Comment by MangelMaxime** [comment]
Hum, strange...

I think if you have dotnet 2+ it should works because the CI is Green.
