### ISSUE TITLE
Add more encoders/decoders for primitive types

### ISSUE THREAD

**Issue by toburger** [MangelMaxime/Thoth#29]
I often have to write my own encoder/decoder implementations for primitive types like for Dates or decimals.

Newtonsoft.Json.Linq.JValue has 15 overloads so they should be supported OOTB and I think it would make sense to include decoders/encoders for the following primitives:

* uint64
* int64
* decimal
* char
* System.DateTime
* System.DateTimeOffset

optional:
* System.TimeSpan
* System.Uri
* System.Guid

What do you think?

**Comment by MangelMaxime** [comment]
I do agree we should add more primitives types.
All of them should be possible except `System.DateTimeOffset` I think it's not implemented in Fable yet.

**Comment by MangelMaxime** [comment]
Same not sure if Fable support `uint64`

**Comment by MangelMaxime** [comment]
Thoth.Json v2 include more primitives types by default.

I will probably not release new version of v1, as v2 will be the default when Fable 2 will be released.
