### ISSUE TITLE
Some encoders are missing in Thoth.Json 2 alpha (decimal, guid)

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#41]
We added Decoders for guid and decimal, but I forgot about the encoders 😅

I'll try to send a PR later and check if there are other missing encoders

**Comment by MangelMaxime** [comment]
When you added then, I was surprise that this code was enough :)

```fs
        let toString (space: int) (value: obj) : string =
            JS.JSON.stringify(value, (fun _ v ->
                match v with
                // Match string before so it's not considered an IEnumerable
                | :? string -> v
                | :? System.Collections.IEnumerable ->
                    if JS.Array.isArray(v)
                    then v
                    else JS.Array.from(v :?> JS.Iterable<obj>) |> box
                | _ -> v
    ), space)
```

And forget to ask you about it 😅

And cool more tests to come hihi :p

**Comment by MangelMaxime** [comment]
What should be done to fix this issue ?

**Comment by MangelMaxime** [comment]
I guess, we need to add Encoders for all the types in fact no ?

Like DateTime, DateTimeOffset, etc.

I will add them
