### ISSUE TITLE
Cannot import into SAFE stack templated project

### ISSUE THREAD

**Issue by blair55** [MangelMaxime/Thoth#42]
I have created a new project via the latest SAFE template.

```
$ dotnet new -i SAFE.Template
$ cd my-project
$ dotnet new SAFE -la fulma-basic -jd yarn -lang F#
```
I installed `Thoth.Elmish.Toast` by adding it to the `Client` group of `paket.dependencies` and then adding it also to the Client project `paket.references`.

I then run `paket install`.

Reference to `Thoth` cannot be found by Ionide in vscode but no error message explains what happened. To find out, I removed the `storage: none` directive from the `Client` group in the `paket.dependencies` file.

I was then given some feedback which was:

```
.../Thoth.Elmish.Toast/fable/obj/Thoth.Elmish.Toast.fsproj.proj-info.targets'
.../packages/client/Thoth.Elmish.Toast/fable/Thoth.Elmish.Toast.fsproj(22,5):
error MSB4019: The imported project ".../packages/client/Thoth.Elmish.Toast/.paket/Paket.Restore.targets" was not found.
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by MangelMaxime** [comment]
I can't repro it. 

I followed your instructions and I get intellisense working etc.

@forki Does the error mean something to you ?

**Comment by blair55** [comment]
I think you are right. I was testing in a project that is only a couple of days old so thought there must be a problem. However, I have re-tried in a fresh scaffolded template and it works fine. Apologies!
