### ISSUE TITLE
Make it easier to write custom decoders

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#48]
When I write a custom decoder it always takes a while for me to remember how to build the error part. If this happens to me that I know the codebase I assume it will be worse for other users. I think it's partly because the high-level functions return `Result<'T, string>` but decoders require `DecoderError`.

My suggestions to improve the situation would be:

- Add an example of how to write a custom decoder in the documentation.
- Add a helper to easily dispatch errors. For example, I have the following decoder:

```fsharp
    module Decode =
        let serverDate : Decode.Decoder<DateTime> =
            fun path value ->
                Decode.string path value
                |> Result.bind (fun value ->
                    match Common.tryParseServerDate value with
                    | Some value -> Ok value
                    | None ->
                        let reason =
                            "Cannot parse server date: " + value
                            |> Decode.ErrorReason.FailMessage
                        Decode.DecoderError(path, reason) |> Error)
```

We could reduce the last lines if we had a helper like this (I'm not very convinced of the name because it's too similar to F# `failwith`):

```fsharp
let failwithMsg path reason =
    Decode.DecoderError(path, Decode.ErrorReason.FailMessage reason) |> Error
```

- Not entirely related, but I always wonder why `errorToString` is private. Can it be made public in case someone needs it? (tbh, I've never actually did but...)

**Comment by MangelMaxime** [comment]
Yep, I should add documentation on how to write a custom decoder.

Also, you in your case you can work at a higher level and just compose existing decoders :).

Example taken from my production code:

```fs
   let fromUtcIsoAsLocal<'a> : 'a -> Result<DateTime,Decode.DecoderError> =
        Decode.string
        |> Decode.andThen
            (fun str ->
                DateTime.Parse str
                |> (fun d -> d.ToLocalTime())
                |> Decode.succeed
            )

    let intFromString<'a> : 'a -> Result<int,Decode.DecoderError> =
        Decode.string
        |> Decode.andThen (fun value ->
            match Int32.TryParse value with
            | true, num ->
                Decode.succeed num
            | _ ->
                sprintf "`%s` isn't a valid integer" value
                |> Decode.fail
        )
```

About `errorToString`, it was public at first but some people started to over use it and make their code harder to maintain. Also, people should never need to call it. The Thoth.Json know when et how to call it to give the correct reports.
