### ISSUE TITLE
Json: `Map` collection decoder

### ISSUE THREAD

**Issue by et1975** [MangelMaxime/Thoth#62]
Map used to roundtrip in Fable1, but Thoth has no decoder for this type of collection and autogenerated decoder simply fails.

Ideally there would be support for it directly in Thoth.Json.

**Comment by et1975** [comment]
Gah, it's [there](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Json/Decode.fs#L617), just not mentioned in the docs.

**Comment by MangelMaxime** [comment]
Yes I didn't list of the decoders in the documentation because at first we only had the primitives listed. 

I probably should create a dedicated pages somewhere but not sure of the style to apply :)
