### ISSUE TITLE
Add autodecoder for Set<'a>

### ISSUE THREAD

**Issue by forki** [MangelMaxime/Thoth#68]
using lists for now, but this would be cool to have

**Comment by MangelMaxime** [comment]
I guess it should be possible to do something similar to `Map<'Key, 'Value>`

For reference:
- [Source Fable](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Json/Decode.fs#L959)
- [Source .Net](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Json.Net/Decode.fs#L1026)
