### ISSUE TITLE
Should we remove decimals and BigInts from auto decoder?

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#77]
When using Decode.Auto, Fable adds a reference to the Bigint and Decimal library in the replacements library. These files will increase the bundle size even if most devs won't really use them in their apps. Would it be better to throw an error and tell users who need those types to use a manual decoder?

**Comment by MangelMaxime** [comment]
If this increase a lot the bundle size we probably should indeed.

I am also thinking of allowing people to register manual decoders in their `Auto` decoders but I am not sure about that yet.

I do think that using manual decoders to control auto decoders is the way to go. And will wait for people feedback about their needs before adding this kinding of features.

**Comment by alfonsogarciacaro** [comment]
Ok, let's keep all the standard types to avoid surprises :)
