### ISSUE TITLE
Bug: Json optional record fields do not decode if the contained type is decoded with oneOf.

### ISSUE THREAD

**Issue by phillipbaird** [MangelMaxime/Thoth#79]
Hello there.  Think I've found a bug in Decode.fs.

### Summary
A record with a field of type `'a option`, will fail to decode if `'a` is decoded using `oneOf` and the field value is `None`.

### Example

Given these types...

```fs
type YingYang =
    | Ying of int
    | Yang of string
    static member encoder = function
        | Ying x -> Encode.object [ "Ying", Encode.int x ]
        | Yang x -> Encode.object [ "Yang", Encode.string x ]
    static member decoder =
        Decode.oneOf [
            Decode.field "Ying" Decode.int |> Decode.map Ying
            Decode.field "Yang" Decode.string |> Decode.map Yang
        ]

type RecordWithOption =
    { yingyang : YingYang option }
    static member encoder x =
        Encode.object [ "yingyang", Encode.option YingYang.encoder x.yingyang ]
    static member decoder = 
        Decode.object (fun get -> { yingyang = get.Optional.Field "yingyang" YingYang.decoder } )
```

The following test case will fail...
```fs
testCase "get.Optional.Field returns None if optional type is decoded using oneOf." <| fun _ ->
    let json = """{"yingyang":null}"""
    let expected = Ok({ yingyang = None})
    let actual = Decode.fromString RecordWithOption.decoder json
    equal expected actual
```

### Suspected Cause

The implementation of the `get.Optional.xxx` members in the `Decode.object` function do not handle a `BadOneOf` error caused by the `null` value representing the `None`.

Here is one of the match expressions I suspect needs changing.
```fs
match decodeValueError path (field fieldName decoder) v with
| Ok v -> Some v
| Error (_, BadField _ ) -> None
| Error (_, BadType (_, jToken))
| Error (_, BadPrimitive (_, jToken)) when jToken.Type = JTokenType.Null -> None
| Error error ->
    raise (DecoderException error)
```
[Decode.fs lines 639 - 645](https://github.com/MangelMaxime/Thoth/blob/1193db51c1b940c5f82bce0e92d854f6b16d1b67/src/Thoth.Json.Net/Decode.fs#L639-L645)

The match expressions in the `get.Optional` members possibly should be extended to include a pattern to cover this null case...
```fs
| Error (_, BadOneOf (_, jToken)) when jToken.Type = JTokenType.Null -> None
```

### Workaround

A way to work around the problem is to change the decoding of the optional field so that it is required and by wrapping the decoder for the contained type in a `Decode.option`.

i.e. This...
```fs
Decode.object (fun get -> { yingyang = get.Optional.Field "yingyang" YingYang.decoder } )
```
becomes...
```fs
Decode.object (fun get -> { yingyang = get.Required.Field "yingyang" (Decode.optional YingYang.decoder) } )
```
### Note

This has only been tested with Thoth.Json.Net, although a look at the Thoth.Json version for Fable looks like it will have the same issue.

Thank you for this library and taking the time to look at this issue.

**Comment by MangelMaxime** [comment]
Hello @phillipbaird , thank you for the detailed issue.

I think your analysis of the problems is correct. And yes both .Net and Fable version implements the same behavior and probably both have the same bug in it.
