### ISSUE TITLE
[Discussion] What should be promoted as the "right" approach

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thoth#80]
Thoth.Json is primarily focused on letting you write custom coders for your type. However, when removing JSON serialization in Fable 2, we gave it some auto (de)serialization capabilities. As expected, people are using these auto (de)serializers to make the Fable 2 upgrade easier. But there're some issues with this approach:

- `Decode.Auto` makes reference to most of the "primitive" types supported by Fable. This pulls code from Fable polyfills increasing the bundle size even if the types are not used in the app at all: datetimes, maps, decimals, bigints (specially the last two and probably also longs).
- As soon as the user wants to use a custom decoder for one type, they need to write decoders for all the other types.
- The map is compiled as an arrays of arrays. This is done to avoid problems when the key is not easily converted to string, but it's confusing as most users will expect them to transform to JSON objects.

I'm the first one to acknowledge how difficult is to maintain a "magic" serialization library, and I'm super happy of removing it in Fable 2. But on the other hand, as we're promoting F# fullstack, users will expect to have an easy way to share the types between client and server without having to write so much boilerplate.

Possible solutions:

- Leave it more or less as is and tell users that as soon as they have specific needs they should write custom decoders for the whole domain.
- Try to balance custom and auto decoders, for example, by allowing to pass a dictionary/function with custom decoders that could override the default ones.
- Have a different library that focus on the auto serialization? Could make sense to promote @zaid-ajaj SimpleJson like this? (though, for what I've seen SimpleJson has similar problems to those listed above).

> I'm adding a fix to reflection in Fable 2.1 to prevent code duplication when calling `typeof` several times on related types.

**Comment by MangelMaxime** [comment]
As a side note, I don't like some of the decoders "custom". Custom had another meaning in Thoth.Json v1 and still have another meaning for people coming from Elm.

I would prefer to speak about **manual** and **auto** decoders.

------------------------

> As soon as the user wants to use a custom decoder for one type, they need to write decoders for all the other types.

I think if we works on #65 we should be able to control the decoders using manual decoders. And have something like that:

```fs
type ComplexTypeA =
    // I am using class end so I don't have to write a lot of code for the demo
    class end

    static member Decoder = 
        Decode.Auto.generateDecoder<ComplexTypeA>()

    static member Encoder (x : ComplexTypeA) = 
        Encode.Auto.generateEncoder<ComplexTypeA>()

type SimpleTypeB =
    // I am using class end so I don't have to write a lot of code for the demo
    class end

    static member Decoder = 
        Decode.Auto.generateDecoder<SimpleTypeB>()

    static member Encoder (x : SimpleTypeB) = 
        Encode.Auto.generateEncoder<SimpleTypeB>()

type Test =
    { FieldA : ComplexTypeA
      FieldB : SimpleTypeB }
    
    static member Decoder =
        Decode.object (fun get ->
            { FieldA = get.Required.Field "fieldA" ComplexTypeA.decoder
              FieldB = get.Required.Field "fieldB" SimpleTypeB.decoder }
        )

    static member Encoder (v : Test) =
        Encode.object [
            "fieldA", ComplexTypeA.Encoder v.FieldA
            "fieldB", SimpleTypeB.Encoder v.FieldB
        ]
```

> Have a different library that focus on the auto serialization? Could make sense to promote @Zaid-Ajaj SimpleJson like this? (though, for what I've seen SimpleJson has similar problems to those listed above).

Any library that will really on reflection will have this problem. Unless we load the polyfills in an asynchrone way. Which then turn in a lot of problems especially for startup time.

> Leave it more or less as is and tell users that as soon as they have specific needs they should write custom decoders for the whole domain.

No, we should work on the current feature and works on improving mixing auto decoders and manual decoders. 

> Try to balance custom and auto decoders, for example, by allowing to pass a dictionary/function with custom decoders that could override the default ones.

I am not for this solution, this mean the users will need to modify a dict based on its usage of the types. Which are potentially deeply nested in his code. 

This is something that I had when working on the FormBuilder library and it was a really unpleasant experience.

IMO if people are using auto features they have to understand that there is a price for it and they need to be more rigorous when writing their code.

------------------------

I do understand why people prefers auto decoders. But I really do think that using the manual decoders to control the auto decoders is the way to go. The compiler will help you will that so you will still benefit of the types system, intellisense etc. 

What's missing for that is #65 so people can write the decoders and encoders.

If we go we some kind of a config registration, then the compiler will not be able to help you. You will most of the time end up going back and forth on your config things.

**Comment by MangelMaxime** [comment]
And thanks you I now understand why map as converted as arrays by the auto decoders.

> The map is compiled as an arrays of arrays. This is done to avoid problems when the key is not easily converted to string, but it's confusing as most users will expect them to transform to JSON objects.

I still think #75 is needed in order to be sure we are supporting the same types as auto encoders and auto decoders. This is not the case right now. :)

**Comment by MangelMaxime** [comment]
For Girafe I have a working version [here](https://github.com/SAFE-Stack/SAFE-BookStore/pull/367/files).

**Comment by johannesegger** [comment]
Auto decoders are great when you don't care about the actual output - you just want to send it over the wire. Manual decoders are great when you do care about the actual output, e.g. when you save it to a file or when the serialized version is persisted or lives a bit longer.  
So I think there are scenarios for both type of decoders.  
Maybe it's possible to simplify writing manual [en|de]coders if you just had to write one of them and get the other one for free? Would that be possible (of course without any reflection)?

**Comment by MangelMaxime** [comment]
> So I think there are scenarios for both type of decoders

Yes, there is place for both of them. I personally think we should make mixing them easier. For the decoders, we are already here but not for the encoders.

> Would that be possible (of course without any reflection)?

I do have plan to make the generation of Decoder/Encoder by using a generator #20. The tool by itself was kind of working for Thoth.Json v1 but I never really invest a lot of time in it. So when you wanted to write a manual decoder, you could generate it and fix the missing/special parts of it.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime At the end I've come up with this for Giraffe. This should be quite performant because it's writing directly in the response body stream and doesn't need the intermediate string representation. You can use it with sequences too. The only problem is users must avoid `Successful.OK` because the Giraffe will apply the default JSON serialization causing problems in the server. Maybe Thoth.Json.Giraffe could shadow this.

```fsharp
module Json =
  open System.Threading.Tasks
  open Microsoft.AspNetCore.Http
  open FSharp.Control.Tasks.V2
  open Newtonsoft.Json
  open Newtonsoft.Json.Linq
  open Thoth.Json.Net
  open Giraffe

  let okRaw (token: JToken) =
    fun (next : HttpFunc) (ctx : HttpContext) -> task {
        ctx.SetStatusCode 200
        ctx.SetContentType "application/json; charset=utf-8"
        use stream = new System.IO.StreamWriter(ctx.Response.Body, NewLine = "\n")
        use jsonWriter = new JsonTextWriter(stream)
        do! token.WriteToAsync(jsonWriter)
        return Some ctx
    }

  let ok (body: 'T) (encoder: Encode.Encoder<'T>) =
    encoder body |> okRaw

  let okSeqRaw (tokens: JToken seq) =
    fun (next : HttpFunc) (ctx : HttpContext) -> task {
        ctx.SetStatusCode 200
        ctx.SetContentType "application/json; charset=utf-8"
        use stream = new System.IO.StreamWriter(ctx.Response.Body, NewLine = "\n")
        use jsonWriter = new JsonTextWriter(stream)
        jsonWriter.WriteStartArray()
        for token in tokens do
          do! token.WriteToAsync(jsonWriter)
        jsonWriter.WriteEndArray()
        return Some ctx
    }

  let okSeq (xs: 'T seq) (encoder: Encode.Encoder<'T>) =
    xs |> Seq.map encoder |> okSeqRaw

  let readBody (ctx: HttpContext) (decoder: Decode.Decoder<'T>): Task<'T> = task {
    let! json = ctx.ReadBodyFromRequestAsync()
    return
      match Decode.fromString decoder json with
      | Ok value -> value
      | Error er -> failwith er
  }
```

**Comment by alfonsogarciacaro** [comment]
> I am not for this solution, this mean the users will need to modify a dict based on its usage of the types. Which are potentially deeply nested in his code.

@MangelMaxime Consider the following example:

```fsharp
type Foo =
    | Foo of int
    // For some reason I want to serialize Foo as int
    static member Encode (x: Foo) =
        let (Foo i) = x
        Encode.int i

type ComplexTypeA =
    { FieldA: string
      // Many more fields here
      FieldZ: Foo }
    // I want to use Encode.Auto.generateEncoder() here (when it's available)
    // but one of the fields is Foo which has a manual encoder, so I can't
    static member Encode (x: ComplexTypeA) =
        Encode.obj [ ... ]

type Test =
    { FieldA : ComplexTypeA
      FieldB : SimpleTypeB }    
    static member Encoder (v : Test) =
        Encode.object [
            "fieldA", ComplexTypeA.Encoder v.FieldA
            "fieldB", SimpleTypeB.Encoder v.FieldB
        ]
```

Just because we want to serialize `Foo` in a particular way, we cannot use auto encoders in any type that uses it. And there are other, worser, corner cases: for example, we can add the `Foo` field to a type later on and forget to change from auto to manual encoder, or `Foo` can be in a nested type and we don't take this into account when picking an auto encoder.

However, if we had the dictionary, we only need to remember to update it, whenever we want to have a manual encoder for some types.

```fsharp
let manualEncoders = Map [
    typeof<Foo>.FullName, (fun (x: Foo) ->
        let (Foo i) = x
        Encode.int i)
]

// An alternative would be to use a function instead of a dictionary
let manualEncodersFn (t: Type) (x: obj) =
    if t.FullName = typeof<Foo>.FullName then
        let (Foo i) = x :?> Foo
        Encode.int i |> Some
    else None

type ComplexTypeA =
    { FieldA: string
      // Many more fields here
      FieldZ: Foo }
    static member Encode (x: ComplexTypeA) =
        Encode.Auto.generateEncoder(manualEncoders)
```

**Comment by MangelMaxime** [comment]
Hum... You are probably right @alfonsogarciacaro 

In fact, I don't think we have a perfect solution others than removing the auto features :trollface: 

More seriously, I think here all the discussion is more focused on the `Auto` decoders API that is too limited perhaps. And perhaps adding new features to it is the way to go.

We need to think really carefully our moves because it can have big good or bad impact on user code.

One thing I am more or less certain of is that related to #77 I would consider that `Auto` features have to support most/all the F# types by default. And yes this is at the price of the bundle size but I am personally perfectly ok with that.

So then people, will "only" have to worry about their own types.

**Comment by MangelMaxime** [comment]
Also we would need to "real" example or case we want to support so everyone can understand have the same examples in mind to help communicates.

**Comment by alfonsogarciacaro** [comment]
Continue discussion in #84
