### ISSUE TITLE
[FormBuilder] Take a look for react performance

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Thoth#90]
I think the library "BasicFields" should by default offer optimized react experience.

**Comment by fergusmeiklejohn** [comment]
I think BasicFields should offer a "withDefaults" experience. Most apps might only ever need BasicFields.

**Comment by MangelMaxime** [comment]
What do you mean by "withDefaults" ?

**Comment by fergusmeiklejohn** [comment]
Ideally we would have the most common types of field and they would come with sensible defaults including validation as standard.  I was wondering about using validator.js for this:
https://github.com/chriso/validator.js
https://www.npmjs.com/package/@types/validator
Like you know how in html a Form at it's most basic is:
```
  <form>
    <input name="name" placeholder="Name" />
    <input name="email" placeholder="Email" type="email" />
    <input type="submit">
  </form>
```
I wonder if we could make BasicFields (maybe in Fulma?) as close as possible to this sort of simple experience, but of course with all the power of F# and this library behind the simple interface

Apologies this has little to with React, more to do with "optimized experience"

**Comment by MangelMaxime** [comment]
I moved this issue to another repository, and further work will take place there.
