### ISSUE TITLE
AutoDecode of seq

### ISSUE THREAD

**Issue by SCullman** [MangelMaxime/Thoth#96]
```fsharp
open Thoth.Json
let json = "[ \"A\" ]"

// returns Ok [A]
Decode.Auto.fromString<string list>( json) |> printfn "%A"

// returns Ok A
Decode.Auto.fromString<string array>( json) |> printfn "%A"

// Error Error at: `$`
// I run into a `fail` decoder: Class types cannot be automatically deserialized: 
// System.Collections.Generic.IEnumerable`1[System.String]
Decode.Auto.fromString<string seq>( json) |> printfn "%A"
```

It would be nice if Sequences were supported.

**Comment by MangelMaxime** [comment]
I indeed don't really know sequence so I am not sure of the right approach. But indeed, my way to go would be to decode it like a `list` and then directly cast to `seq`. 

@alfonsogarciacaro Would this be the correct solution ? 

Also is `System.Collections.Generic.IEnumerable` always a `seq` ?

**Comment by SCullman** [comment]
> Sequences are represented by the seq<'T> type, which is an alias for System.Collections.Generic.IEnumerable. [Link](https://docs.microsoft.com/de-de/dotnet/fsharp/language-reference/sequences)

I would expect decoding with ``array`` or ``list``, and then the cast to ``seq``.

@xdaDaveShaw Well, I had a  problem decoding ``list``s in IE11, and it turned out to be a well known problem with [polyfill.io](https://github.com/fable-compiler/Fable/issues/1654). And on the way to solve my problem I tried also  ``array``s and finally ``seq``.

**Comment by MangelMaxime** [comment]
Ok thanks for taking a look at the documentation @SCullman :)

**Comment by SCullman** [comment]
I was curious whether/ where I would find the alias for ``seq`` in source, just for my own understanding. To my surprise I couldn't find it directly in ``Fable.Core``, but then in in [FSharp.Core/prim-types](https://github.com/fsharp/fsharp/blob/cb6cb5c410f537c81cf26825657ef3bb29a7e952/src/fsharp/FSharp.Core/prim-types.fs#L3245). :
 `` type seq<'T> = IEnumerable<'T>``

**Comment by MangelMaxime** [comment]
Now tracked in https://github.com/thoth-org/Thoth.Json/issues/26
